name: JS Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: hello-action
        uses: ./.github/actions/hello-world  
        with:
          first-greeting: "Aashish"
          second-greeting: "Rathore"
      - name: External Api
        uses: ./.github/actions/joke-action
      - name: Issue Create
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          joke: ${{ steps.jokes.outputs.joke-output }}

        